/**
 * Who the clinic is. Name, address, contact, tagline, hero photography.
 *
 * Every value here is taken from a file in ../../../Resources and can be
 * checked against it:
 *  - Marketing/Brand Identity/Letterhead/MELA SKIN - Letterhead_DRAFT.docx
 *    (address, phone, email, site, tagline)
 *  - Marketing/Brand Identity/MELA SKIN - Visual Identity Branding
 *    Presentation.pdf (descriptor lockup, tagline, address)
 *  - Corporate/Entity Documents/PIN Certificate-Mela Skin Limited.pdf
 *    (registered name)
 *
 * Anything the clinic has NOT confirmed lives in ./placeholders.ts instead,
 * where it renders in visible [square brackets] so it cannot ship unnoticed.
 */

import { heroSampleCredit, heroSamples, photos } from "./placeholders";

export const brand = {
  name: "Mela Skin",
  entity: "Mela Skin Limited",
  descriptor: "Dermatology & Cosmetic Clinic",
  tagline: "Richer. Radiant. You.",
  address: {
    line1: "The Atrium, 4th Floor",
    line2: "88 Serenity, Westlands",
    city: "Nairobi",
    country: "Kenya",
  },
  phone: "+254 7 447 7777",
  phoneHref: "tel:+254744777777",
  email: "info@melaskin.com",
  site: "www.melaskin.com",
  /**
   * THE HOME HERO. Two strings, and that is the whole first screen.
   *
   * It carried a tagline, an eyebrow, two lines of copy, a large brandmark and
   * a framed image stack. All of that is off it now:
   *
   *   Mo / operations, 26 Aug 00:47:02 — "my concern with the draft is that
   *   it's too busy. Even when I look at it, I'm not sure what exactly to look
   *   at … it would be best if we can do it in a clean format that feels like
   *   elegance and excellence."
   *
   *   Dr. Abseret Hailu, 00:56:08 — "I want our brand to be more clean. I don't
   *   want it to be so busy."
   *
   *   Negasi, 00:57:11 — "even if we are having the background image we can
   *   minimize the contents that we display on the first screen."
   *
   * What is left is the tagline (Aser, 00:37:22: "the text is strong, like the
   * 'richer, radiant you' reads well"), one sentence, and two buttons, over one
   * full-bleed image. The descriptor and the address are in the header lockup
   * and the footer, where they were already.
   */
  hero: {
    line: "Medical and cosmetic dermatology built for melanin-rich skin, on one record and under one roof.",
    /**
     * The committed hero's two lines, kept for the demo variant that restores
     * it (components/hero/HeroOriginal.tsx). The current hero carries one line
     * and no address: the descriptor is in the header lockup a few centimetres
     * above and the address is on /contact, in the footer and in the JSON-LD,
     * so on the first screen they were the third and fourth things saying what
     * the other two already said.
     *
     * Named `legacy*` so nothing reaches for them by accident. They go when the
     * team picks a hero.
     */
    legacyLine1: "Cosmetic & medical dermatology clinic.",
    legacyLine2: "The Atrium, 4th Floor, 88 Serenity, Westlands, Nairobi.",
  },
} as const;

/**
 * THE HERO'S FULL-BLEED GROUND.
 *
 * The 26 Aug review of four reference sites landed on one image filling the
 * first screen with the clinic's name over it — the Canadian site's frame with
 * Elevate's lockup. Abseret [00:48:09]: "I also like the Elevate one where they
 * had the clinic name … This one I like the most. It was a little bit cleaner."
 *
 * `heroFrames` is the eventual sequence, and it is Mo's [00:47:02]: "it shows
 * the entrance, the reception, the waiting area, and then flips into the
 * cosmetic procedures … and then the next, medical procedure. So possible
 * potential clients are able to see our clean space, they're able to see a
 * glimpse of the cosmetics and the medical, on the landing page." Dr. Gachanja
 * [00:49:44] called that a blend of the two reference sites, which it is.
 *
 * NONE OF THE THREE EXISTS YET. Aser [00:49:00]: "one thing is, we don't have
 * the clean space pictures yet." So all three are empty and the hero slides
 * through `heroSamples` instead — three licensed stock interiors, credited on
 * the page. Point a `src` here at the clinic's own photograph and it takes over;
 * fill all three and the samples are never used again.
 */
export const heroFrames = [
  { id: "reception", ...photos.reception },
  { id: "cosmetic", ...photos.cosmetic },
  { id: "medical", ...photos.medical },
] as const;

/** Re-exported so components take the hero's samples from one place. */
export { heroSampleCredit, heroSamples };

/**
 * The last-resort ground, used only if the frames above and the samples are all
 * empty: the official 4_Pattern motif at architectural scale over Primary 2,
 * vignetted. Generated by `scripts/build-brand-assets.py` from the brand
 * package, so it is real artwork rather than a stand-in for one.
 */
export const heroBackground = {
  id: "brand",
  src: "/images/hero-background.webp",
  label: "Mela Skin",
  caption: null,
  alt: "",
} as const;
